version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    container_name: library_db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: library_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: library_app
    command: /bin/sh -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8080 --reload --redis-url ${REDIS_URL}"
    volumes:
      - ./:/code
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PORT=${PG_PORT}
      - REDIS_URL=${REDIS_URL}

volumes:
  db_data:
  redis_data: